language: python
dist: xenial
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
- python setup.py -q install
addons:
  sonarcloud:
    organization: kbytesys-github
    token:
      secure: OD/SFPI9V9+MXbBGyD28sEixy5vDtF9uWZAVQzMV4TiAbI6CstspUYWOJ7seQzBJ2hfA1Odh5oDlSZC/NNgOrUTR/5GfW3UIAXfFxQQ8rpWUhaDUGCxAi1D1mPgOQjrYzO8P01e3pDHxKAaD+YfUJ4LQ8yI0+/HxkbMp8O8ewkCoKAWLzmKTOHXzHTgnFUgD/rZgxB3/3FSO7BokeCzprdiSJPByMLGb/fqYN6zbQJm0lA1/MaFjYfhsq1+WL0GUr3GZ5e07xzY7CFAnhXZogerXv6kwCDnotdKm19BJiEbFHfSDmXJk1UwH+7BdNnDPdwmAUjvc63BfHUZxDefg+/3v4bx1BQnpQ7RhBNo9wwVry0BH2x3tk3KEQcuk9JSKymbGugOL/vh+9xhzdMtwIKQahecV9DnEuF6Of58uXCP968nwjUzsYEJi01QKryzB6kGUC8YL07FxH0Z3MKOf/zAJFYmhiCg6zcHwRV8fYBdfEad1qnPz/SSbpEyIsu7GWpWJZn7v3NVCVqlPOi5/jj7OOQ/3MBLLQc9aAQ0uVGGtw/R3lIQbG8tbIWRWvUT0o50L+0XjW0HmYzVsrxEexeYtcT0Buien1Wc5D+/goooXPd38DL0hplZe2Sma01p3Vr2g0c5iD+iHLYzZNSExg8FYCuEtV29bUgcPwgI5NZ4=

script:
- tox
- sonar-scanner
deploy:
  provider: pypi
  skip_existing: true
  user: kbyte
  distributions: sdist bdist_wheel
  password:
    secure: aoMwfMufWOyOOvJAz/sXRL5v7xs/vr1WMpr+SNNO9lBKHCTCAXSVtz9zQjVfIAV0cbjuCv94Bw2/n7nom1SKjwh3nB0BXVjX+0O2R93zNhwsYdXoA5mLEpeELcW/rWygk/ECM33dRnL0JTkzYnPRSRgPTO1QSjzpRiXhzmFjO1COQgAafL3AqtDoQwmFjHXMYeFvyyp4jSssh/1GpEv33pexIZ+5F0uCEiXxudBhYoFlJIeZ2aLe+ngTR5cGqgqjpVR7dU2qrWYs0JMEU9eQazQcNEdVp7bEhj+I/5VTD1Md7hDbqRI+/zEIcsZ4g42kbW+y3wH95Nf196+lyNskihhruVMVN9VfbLr4aLwwvXF/SjsIoUL91ZcEhetoDzsmyS23zEvY1rsjAFRgSk+oCoC2RTQjOt1f6pomdjk3FR7jCv6WhH0GM1ZDZIKQEC4I4nz0gVTfFKmi4X2E+yU+AuEcMGjoVTmtZtqYMaTRUn5vYMgKxVP8RY+qDs9iqweShJtyGSXcBqbDN0bnV3T4R3KzdbMn83JlQgjNlTzbwC5O4Bq8tTDxyG9W/HyX6b+RQTjkbprNYTHJWop6zhZMUqh4JCq5HA49tDV7wXHFGkSNC8cT0xV2TdLFWcJrKCALH925S9Ynop/aLBm7uwItetKOmpVYtCyerTGbA+nP1Yw=
  on:
    tags: true
    python: '3.6'
