language: python
dist: trusty
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
- python setup.py -q install
addons:
  sonarcloud:
script:
- tox
- sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -X
deploy:
  provider: pypi
  skip_existing: true
  user: kbyte
  distributions: sdist bdist_wheel
  password:
    secure: $PYPISECRET
  on:
    tags: true
    python: '3.6'
